### ISSUE TITLE
公共日语不会自动答题和下一个视频

### ISSUE THREAD

**Issue by ra1nv** [CodFrm/cxmooc-tools#23]
win和mac都是用chrome  用的1.4版本

点击background page
报错是_generated_background_page.html:1 Error in response to storage.set: ReferenceError: message is not defined
    at Object.callback (chrome-extension://dipckechdcekbmgkjlmefhmpanmkedkf/src/background.js:1:951)
    at XMLHttpRequest.n.onreadystatechange (chrome-extension://dipckechdcekbmgkjlmefhmpanmkedkf/src/background.js:1:888)

**Comment by ra1nv** [comment]
http://blog.sina.com.cn/s/blog_12e78f7230102xuh1.html   这里有题库

**Comment by ra1nv** [comment]
博主加油！   能后台挂机已经很感谢了~

**Comment by CodFrm** [comment]
@ra1nv 填入答案以实现

**Comment by CodFrm** [comment]
自动挂机实现
