### ISSUE TITLE
npm run server出现错误

### ISSUE THREAD

**Issue by yosonia** [CodFrm/cxmooc-tools#81]
在Ubuntu中输入npm run server出现如下错误
Error: Cannot find module './config'
Require stack:
- /root/cxmooc-tools/src/server/listen.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/cxmooc-tools/src/server/listen.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cxmooc-tools@2.1.0 server: `node src/server/listen.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cxmooc-tools@2.1.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-26T14_16_14_078Z-debug.log

**Comment by CodFrm** [comment]
这是一个本地的配置文件:
给你一个样例,之后保存在 src/server/config.js
```js
module.exports = {
    env: 'local',
    vcodehost: '8.8.8.8',
    vcodeport: 1000,
    genToken: 'vcodetoken'
}
```

**Comment by yosonia** [comment]
非常感谢帅气的您，还有一个问题，只启动了HTTP Server is running on: http://www.xxxx.com:8080，然后访问https://www.xxxx.com:8081服务是失败的

**Comment by CodFrm** [comment]
@yosonia 

8081是https服务,需要在目录下放入证书,之前的那个 config.js  的env变量改为prod

**Comment by yosonia** [comment]
谢谢，问题解决了，你真帅
